print("Program starting.")
color = input("\nInsert a hex color: ")
print("\nColors")
print(f"- Red {color[1:3]}")
print(f"- Green {color[3:5]}")
print(f"- Blue {color[5:7]}")
print("\nProgram ending.")